spring:
  application:
    name: booking-service
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
server:
  shutdown: graceful
