apiVersion: v1
kind: Secret
metadata:
  name: customer-db-secret
  namespace: car-rental
  labels:
    app: customer-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
  DB_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: fleet-db-secret
  namespace: car-rental
  labels:
    app: fleet-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
  DB_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-db-secret
  namespace: car-rental
  labels:
    app: booking-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
  DB_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: car-rental
  labels:
    app: payment-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
  DB_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
